---
# MySQL/MariaDB Handlers

- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: yes
  become: yes
  listen: "restart mariadb"

- name: reload mariadb
  systemd:
    name: mariadb
    state: reloaded
  become: yes
  listen: "reload mariadb"
