---
# MySQL Handlers

- name: restart mysql
  systemd:
    name: mysqld
    state: restarted
    enabled: yes
  become: yes
  listen: "restart mysql"

- name: reload mysql
  systemd:
    name: mysqld
    state: reloaded
  become: yes
  listen: "reload mysql"
